version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword

  backend:
    build:
      context: ./itfa_backend
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_NAME: mydatabase
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      DATABASE_HOST: db
      DATABASE_PORT: 5432

  frontend:
    build:
      context: ./itfa_frontend
    command: ["http-server", "dist/your-angular-app-name"]
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres_data: