FROM node:20

# Set the working directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the Angular application code
COPY . .

# Build the Angular app
RUN npm run build

# Serve the Angular app
RUN npm install -g http-server
CMD ["http-server", "dist/your-angular-app-name"]

# Expose port 8080
EXPOSE 8080