# Generated by Django 5.0.6 on 2024-06-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='country',
            field=models.CharField(choices=[('greece', 'greece'), ('italy', 'italy')], default='greece', max_length=25),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='tax_type',
            field=models.CharField(choices=[('individual', 'individual'), ('business', 'business')], default='individual', max_length=25),
        ),
    ]
