# Generated by Django 5.0.6 on 2024-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0002_personaldetails_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='gross_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
