# Generated by Django 5.0.6 on 2024-06-05 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0003_personaldetails_total_expenses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='gross_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
