name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: itfa_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1234
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d itfa_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_NAME: itfa_db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1234
      DATABASE_HOST: 127.0.0.1
      DATABASE_PORT: 5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag backend Docker image
      run: |
        docker buildx build --tag ${{ secrets.DOCKER_USERNAME }}/itfa-backend:latest ./itfa_backend

    - name: Build and tag frontend Docker image
      run: |
        docker buildx build --tag ${{ secrets.DOCKER_USERNAME }}/itfa-frontend:latest ./itfa_frontend

    - name: Run backend tests
      run: |
        docker-compose -f docker-compose.yml up -d db
        docker run --network host ***/itfa-backend:latest python manage.py test

    - name: Run frontend tests
      run: |
        docker run --network host ${{ secrets.DOCKER_USERNAME }}/itfa-frontend:latest npm test

    - name: Push backend Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/itfa-backend:latest

    - name: Push frontend Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/itfa-frontend:latest
